# Generated by Django 5.0 on 2023-12-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fairmodel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=265)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fairmodel_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('onnx_model', models.TextField()),
                ('update_description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('fairmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fairmodel')),
            ],
        ),
    ]
