version: '3'
services:
  server:
    build:
      context: .
      dockerfile: fairmodels_backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - graphdb
    volumes:
      - ./fairmodels_backend:/opt/app
    env_file: .env

  graphdb:
    image: ontotext/graphdb:10.4.2
    # image: ghcr.io/maastrichtu-cds/fair_tools_docker-graphdb/docker-graphdb:latest
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g