# Generated by Django 5.0.1 on 2024-02-14 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fairmodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FairmodelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('metadata_id', models.CharField(max_length=255, null=True)),
                ('metadata_json', models.JSONField(null=True)),
                ('metadata_template_id', models.CharField(max_length=255, null=True)),
                ('update_description', models.TextField()),
                ('model_type', models.CharField(choices=[('', 'Default'), ('ONNX', 'Onnx'), ('PMML', 'Pmml')], default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fairmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fairmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output')], default='INPUT', max_length=64)),
                ('field_metadata', models.IntegerField()),
                ('field_model', models.CharField(max_length=255)),
                ('fairmodel_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fairmodelversion')),
            ],
        ),
    ]
