# Generated by Django 5.0.1 on 2024-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairmodelversion',
            name='model_type',
            field=models.CharField(choices=[('', 'Default'), ('onnx', 'Onnx'), ('pmml', 'Pmml')], default='', max_length=64),
        ),
    ]
